---
title: "Welcome To My Blog - Fighting the Good Fight"
author: "Jack Chen"
date: "2026-06-05"
categories: [personal]
---

Hi everyone.

I'd like to share a little bit about my background, in case you wanted to learn more about me. I currently work as an investigational drug services clinical pharmacist, but have had the pleasure of providing care within the acute care continuum since graduating from pharmacy school in 2021. I've moved around quite a lot, from an emergency medicine-heavy PGY-1 experience to even a specialized institution serving the hematology/oncology population, Memorial Sloan Kettering. In between all these opportunities, the gravitas of drug development during COVID-19 and my analytical nature guided me towards the quantitative sciences, in which I recently completed my Master's in Pharmacometrics and Personalized Pharmacotherapy at the University at Buffalo School of Pharmacy and Pharmaceutical Sciences (UBSPPS).

The last 2 years have been challenging, to say the least, but I am happy with how green I've raised my grass. It has been such a pleasure to build my skills within model-informed drug development and the complex intersection of mathematics, statistics, coding, and pharmaceutical sciences that is pharmacometrics. While my professional experience lags behind, there is no contention that the foundational PKPD principles I've learned come from leaders in this field (e.g. Dr. Mager, Dr. Jusko, Dr. Bies, etc). Therefore, I hope this blog serves as a reminder of where I've started and where I'll go - for now, it'll be representing UBSPPS as an proud alumnus.
